baseURL = 'https://tutors-in-action.org/'
languageCode = 'en-us'
title = 'Tutors in Action'

[params]
description = 'We are a team of Malaysian youths hoping to help SPM students achieve their best.'
inspiration = 'Exacerbated by class disruptions during the pandemic, we realised that not everyone had the privilege of receiving one-to-one guidance from teachers on topics they may struggle with.'
aim = 'We aim to assist struggling Malaysian youth who lack academic support primarily through specialised online one-to-one or group tutoring by our own team of bright and accomplished volunteer tutors. Furthermore, we plan to use our platform to expand our reach by means of collaborations, fundraisers and more.'
story = 'Founded in 2020, Tutors In Action Malaysia (TIA) is an independent, student-led national organisation with a mission and vision to provide assistance to underprivileged Malaysian youth, predominantly focusing on aiding and guiding SPM students throughout their SPM journey.<br><br>The organisation, initially formed with the sole agenda of preparing Form 5 students for their SPM national examinations, had acted as a bridge between volunteer tutors and tutees and provided a platform for volunteer tutors to conduct one-to-one lessons with their tutees. We further supported our tutees in achieving their academic goals by curating various resources and engaging in our very own study group. Our project has since expanded past our initial vision and as of October 2022, Tutors in Action Malaysia has been successfully recognised as a national organisation by EROS.<br><br>As TIA continues to expand, we have broadened our prospects to extend our services to the underserved Malaysian youth, be it secondary school students in the B40 community or orphaned children seeking shelter in children’s homes. While our philanthropic efforts once covered only one-to-one tuition, we now envision TIA’s future to be one rich with collaborations, fundraisers, group tutoring and much more.'
pages = [
    ['Home', '/'],
    ['Projects', '/projects'],
    ['Resources', '/'],
    ['About', '/about']
]
impacts = [
    [1462, "tutors recruited"],
    [2254, "tutees impacted"],
    [4228, "hours of tutoring"]
]
socials = [
    ["/svgs/facebook.svg", "https://www.facebook.com/tutors.in.action.malaysia"],
    ["/svgs/instagram.svg", "https://www.instagram.com/tutors.in.action/"],
    ["/svgs/telegram.svg", "https://t.me/TIA_helpbot"],
    ["/svgs/youtube.svg", "https://www.youtube.com/@tutorsinactionmalaysia"],
    ["/svgs/discord.svg", "https://discord.com/invite/7AE6cGVg2Y"],
    ["/svgs/linkedin.svg", "https://www.linkedin.com/company/tutors-in-action-malaysia/"],
    ["/svgs/xiaohongshu.svg", "https://www.xiaohongshu.com/user/profile/62f653c1000000001f005342"]
]

[menu]
[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects"
weight = 3

[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 2

[module]
[[module.mounts]]
source = "node_modules/countup.js/dist"
target = "static/countup"

[[module.mounts]]
source = "node_modules/bootstrap/dist"
target = "static/bootstrap"

[[module.mounts]]
source = "node_modules/jquery/dist"
target = "static/jquery"

[[module.mounts]]
source = "node_modules/jquery.easing"
target = "static/jquery.easing"