baseURL = 'https://tutors-in-action.org/'
languageCode = 'en-us'
title = 'Tutors in Action'
description = 'Connecting SPM students with volunteer tutors.'

[params]
pages = [
    ['Home', '/'],
    ['Projects', '/'],
    ['Resources', '/'],
    ['About', '/about']
]
impacts = [
    [20, "projects lauched"],
    [47, "volunteers recruited"],
    [142, "students impacted"],
    [130, "hours of tutoring"]
]
socials = [
    ["/svgs/facebook.svg", "https://www.facebook.com/tutors.in.action.malaysia"],
    ["/svgs/instagram.svg", "https://www.instagram.com/tutors.in.action/"],
    ["/svgs/telegram.svg", "https://t.me/TIA_helpbot"],
    ["/svgs/youtube.svg", "https://www.youtube.com/@tutorsinactionmalaysia"],
    ["/svgs/discord.svg", "https://discord.com/invite/7AE6cGVg2Y"],
    ["/svgs/linkedin.svg", "https://www.linkedin.com/company/tutors-in-action-malaysia/"],
    ["/svgs/xiaohongshu.svg", "https://www.xiaohongshu.com/user/profile/62f653c1000000001f005342"]
]

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 4

[module]
[[module.mounts]]
source = "node_modules/countup.js/dist"
target = "static/countup"

[[module.mounts]]
source = "node_modules/bootstrap/dist"
target = "static/bootstrap"

[[module.mounts]]
source = "node_modules/jquery/dist"
target = "static/jquery"

[[module.mounts]]
source = "node_modules/jquery.easing"
target = "static/jquery.easing"